name: Secure DevSecOps Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_package:
    name: BUILD-JOB
    runs-on: ubuntu-slim
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    strategy:
      fail-fast: false
      matrix:
        language:
          - javascript-typescript

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: BUILD
        run: npm run build

      - name: TEST
        run: npm test

      - name: Artifact upload
        uses: actions/upload-artifact@v7
        with:
          name: artifact-1
          path: |
            package.json
            package-lock.json
            dist/
